version: "3"
services:
  nextjs-app:
    image: my-nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
      # This means that the port 3000 of the container is mapped to the port 3001 of the host machine
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
